=== adenot/netunne/nexus/core/conf/network.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:annotation>
		<xsd:documentation xml:lang="en">
			Nexus-Core-Service-Network-Configuration
		</xsd:documentation>
	</xsd:annotation>
	
	<xsd:element name="network" type="networkType"/>
	
       <xsd:complexType name="networkType">
              <xsd:sequence>
                     <xsd:element name="interfaces" type="interfacesType"/>
              </xsd:sequence>
       </xsd:complexType>

		<xsd:complexType name="interfacesType">
			<xsd:sequence>
				<xsd:element name="interface" minOccurs="1" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="type" type="ifaceType"/>
							<xsd:element name="assignment" type="assignmentType"/>
							<xsd:element name="address" type="ipType"/>
							<xsd:element name="netmask" type="ipType"/>
							<xsd:element name="network" type="ipType"/>
							<xsd:element name="gateway" type="ipType"/>
							<xsd:element name="weight" type="xsd:integer"/>
						</xsd:sequence>
						<xsd:attribute name="device" type="xsd:string" use="required"/>
					</xsd:complexType>
					<xsd:key name="deviceKey">
						<xsd:selector xpath="."/>
						<xsd:field xpath="@device"/>
					</xsd:key>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	
	
	
	<xsd:simpleType name="ipType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="([0-9]|1?\d\d|2[0-4]\d|25[0-5])\.([0-9]|1?\d\d|2[0-4]\d|25[0-5])\.([0-9]|1?\d\d|2[0-4]\d|25[0-5])\.([0-9]|1?\d\d|2[0-4]\d|25[0-5])"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="assignmentType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="static|dhcp"/>	
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ifaceType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="internal|external|virtual"/>	
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="deviceType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="eth[0-9][:]?[0-9]?"/>
		</xsd:restriction>	
	</xsd:simpleType>	
</xsd:schema>

=== adenot/netunne/nexus/_garbage/network-teste.xml
<?xml version="1.0" encoding="UTF-8"?>
<network xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="network.xsd">
	<interfaces>
		<interface device="eth0">
			<type>internal</type>
			<assignment>static</assignment>
			<address>192.168.100.254</address>
			<netmask>255.255.255.0</netmask>
			<network>255.255.255.0</network>
			<gateway>139.82.111.01</gateway>
			<weight>100</weight>
		</interface>
		<interface device="eth0">
			<type>internal</type>
			<assignment>static</assignment>
			<address>192.168.100.254</address>
			<netmask>255.255.255.0</netmask>
			<network>255.255.255.0</network>
			<gateway>139.82.111.01</gateway>
			<weight>100</weight>
		</interface>
	</interfaces>
</network>
