=== adenot/netunne/nexus/_garbage/catalog.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	<xsd:annotation>
		<xsd:documentation xml:lang="en">
   		Supplier Catalog
		Copyright 2005 Supplier SIE. All rights reserved.
	</xsd:documentation>
	</xsd:annotation>
	
	<xsd:element name="supplierCatalog" type="SupplierCatalogType"/>
		
	
	<xsd:complexType name="SupplierCatalogType">
		<xsd:sequence>
			<xsd:element name="supplierInfo" type="ContactInfo"/>
			<xsd:element name="items" type="Items"/>
		</xsd:sequence>
		<xsd:attribute name="supplierID" type="xsd:string" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="ContactInfo">
		<xsd:sequence>
			<xsd:element name="name"    type="xsd:string"/>
			<xsd:element name="street"  type="xsd:string"/>
			<xsd:element name="city"    type="xsd:string"/>
			<xsd:element name="zip"     type="xsd:string"/>
			<xsd:element name="country" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Items">
		<xsd:sequence>
			<xsd:element name="item" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="title"        type="xsd:string"/>
						<xsd:element name="authors"      type="NameList"/>
						<xsd:element name="publisher"    type="xsd:string"/>
						<xsd:element name="year"         type="xsd:positiveInteger"/>
						<xsd:element name="price"        type="xsd:decimal"/>
						<xsd:element name="quantity"     type="xsd:positiveInteger"/>
						<xsd:element name="deliveryTime" type="xsd:decimal"/>
					</xsd:sequence>
					<xsd:attribute name="itemID" type="xsd:string" use="required"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="NameList">
		<xsd:sequence>
			<xsd:element name="name" minOccurs="1" maxOccurs="unbounded" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	
</xsd:schema>

=== adenot/netunne/nexus/_garbage/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Nasdaq Boom (World of Cracking) -->
<supplierCatalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog.xsd" supplierID="001">
	<supplierInfo>
		<name>Supplier 1</name>
		<street>Street 1</street>
		<city>Lisboa</city>
		<zip>1000-001</zip>
		<country>Portugal</country>
	</supplierInfo>
	<items>
		<item itemID="0312335563">
			<title>Let's Go Spain and Portugal</title>
			<authors>
				<name>Alexandra Moss</name>
			</authors>
			<publisher>Let's Go</publisher>
			<year>2005</year>
			<price>22.99</price>
			<quantity>100</quantity>
			<deliveryTime>0</deliveryTime>
		</item>
		<item itemID="1740593391">
			<title>Lonely Planet Portugal</title>
			<authors>
				<name>Julia Wilkinson</name>
				<name>John King</name>
			</authors>
			<publisher>Lonely Planet</publisher>
			<year>2005</year>
			<price>19.99</price>
			<quantity>100</quantity>
			<deliveryTime>0</deliveryTime>
		</item>
		<item itemID="1400014107">
			<title>Fodor's Italy</title>
			<authors>
				<name>Matthew Lombardi</name>
			</authors>
			<publisher>Fodor</publisher>
			<year>2005</year>
			<price>23.95</price>
			<quantity>100</quantity>
			<deliveryTime>-60</deliveryTime>
		</item>
		<item itemID="1400011086">
			<title>Fodor's Florence, Tuscany, Umbria</title>
			<authors>
				<name>Fodor</name>
			</authors>
			<publisher>Fodor</publisher>
			<year>2003</year>
			<price>17.95</price>
			<quantity>50</quantity>
			<deliveryTime>24</deliveryTime>
		</item>
	</items>
</supplierCatalog>
